settings:
  seed: 0
  task_name: "T_pushing_test"

data:
  out_path: "output/data/${settings.task_name}"
  state_dim: 8
  action_dim: 2
  action_bound: 30
  stem_size: [30, 90] # [10,60]
  bar_size: [120, 30] # [60,10]
  pusher_size: 5
  num_episodes: 10
  num_workers: 1 # 48
  episode_length: 30
  training: True
  saving: True
  visualizing: False
  gif: False
  scale: 100 # normalize the data, (x,y)/scale
  window_size: 500
  augment: False
  enable_hnm: True
  weight_factor: 1 # weight the data in the loss function, exp(w*diff)
  weight_ub: 16 # exp(w*diff)<=weight_ub
  hn_th: 0.03 # pick error>=hn_th

train:
  out_dir: "output/runs/${settings.task_name}"
  train_valid_ratio: 0.9
  activation: "relu"
  architecture: [128, 256, 256, 128]
  n_history: 1
  n_rollout: 6
  n_rollout_valid: 6
  step_weight_ub: 2
  noise: 0 # std of the Gaussian noise to training data
  lr: 0.001
  lr_params:
    adam_beta1: 0.9
  lr_scheduler:
    type: "CosineAnnealingLR"
    enabled: true
  n_epoch: 1000
  batch_size: 128
  lam_l1_reg: 0.0e-8 # 2.0e-4 # l1 regularization
  wandb:
    enabled: false
    project: "${settings.task_name}"
    run_name: "test"
    mode: "online"               # {"online","offline","disabled"}
    log_every: 20                # log every N training iterations
    save_checkpoints: false       # save model checkpoints to wandb  